### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by abete1901th** [mauricelambert/SpyWare#4]
I have a problem installing the spyware: when I copy and paste the "pip install SpyWare" code everything is fine, when I send it as well, but towards the end the error appears: "NameError: name 'packages' is not defined [end of output] note: 
This error originates from a subprocess, and is likely not a problem with pip. 
ERROR: Failed building wheel for SpyWare Running setup.py clean for SpyWare Failed to build SpyWare 
ERROR: Could not build wheels for SpyWare, which is required to install pyproject.toml-based projects"
Do you have any idea how to fix it?

**Comment by mauricelambert** [comment]
Thanks for opening this issue !
 - I found the bug
 - I fix it in few minutes
