### ISSUE TITLE
How does the exe work?

### ISSUE THREAD

**Issue by Arusu-Projects** [mauricelambert/SpyWare#5]
Once you click it, it runs and creates file in the same directory. It does show up in Taskbar and you can end it. But how to remove it and ensure it's gone?

**Comment by mauricelambert** [comment]
Hi, it's an executable (a file) you can remove it with the Windows Explorer, with a command line or other techniques to delete a file. When you run the spyware you have a process without window (you should not see it in the taskbar...) and you can stop the process by killing it, to do it you can use the task manager (`taskmgr.exe`, identify the spyware process with the red icon, *click right* on the process, *click on End task*) or you can use your terminal, identify the process by name with `tasklist`, `powershell`, `wmi` or other techniques to list processes and kill the process with `taskkill`, `powershell` or other techniques to kill a process.
